[providers]
infisical = { type = "infisical", project_id = "52838648-6a12-479a-bad9-6e3543df4998", environment = "prod", path = "/", auth = "universal" }

[secrets]
GITHUB_CLIENT_ID = { provider = "infisical", value = "GITHUB_CLIENT_ID" }
GITHUB_CLIENT_SECRET = { provider = "infisical", value = "GITHUB_CLIENT_SECRET" }
RESEND_API_KEY = { provider = "infisical", value = "RESEND_API_KEY" }
REVOLUT_API_KEY = { provider = "infisical", value = "REVOLUT_API_KEY" }
REVOLUT_WEBHOOK_SECRET = { provider = "infisical", value = "REVOLUT_WEBHOOK_SECRET" }
REVOLUT_SANDBOX = { provider = "infisical", value = "REVOLUT_SANDBOX" }
